language: php
php:
- '7.2'
install: composer install
env:
  global:
  # Routeplanning API key
  - secure: "ZjZLp2cLWRteoRvjzVdtYXCp0aLaPkxCC8BZV4wR6t9DTN9DId/x4Jn4uDl1vU9+uyW9xj/vMj83+hbcepgGQq5CvKq0hVlltjYetYVDQDTem7823PVggN9I8sVuNv5Ts0TG+NH6Dp0w8mGJ012PiFmWPIJWqeYgU+2NJUhHoOao3fXL+V6MjeMYAKrOLy8l8nZhYiMhpFglgS0XxvfOVuMaAd0yUVU19ebknR3+l2Ks/1AF06U5/3wc76p/UAf1c2+mHk7sjNKOk8ZxdIuRQVoQKtbFHI6M98Ato9ka9+m0iwdHGHU7Vzf34UwU6F0a0sxO50rl9+wFFIacPobJO0VTPnUmTdzm2NLCSBkR4CTSuoFVppUwsvTVSN/brBGypgAvNbcS03cddbxFWvaVROtJezffVx4KSyFL7OOpAI2n7qdfLWtb2SABS13FSdUgmwN3ZnK6g7+Lgl4A2HPUx67zPbiagqR84cMl3PcVkY0v23z5bwwF2+sfYHqeroX2ujsl+J4VH3i65rh1UT3RkYcK5iBTbDfaFKOuP42lOQ+Rm0I1UkXANVfDRQY/SH9IcJvGv8InzSqPCdbhR5Y4zspEaxJYrN2oQPoBA5FhTpEAsEIVq25Iu81ipq2FHTj9fTeRDk0QiB9Dmpl5AamzjZcIlgwQqrXTgMeGNifNe1Y="
  # Timetables API key
  - secure: "AmMUElmZLuGV9xWFVe736oZ3euYgMYDSSP3ElB8sgQHeRNn2IV2UgFJxqswp0+MmSuO54DJdWPU1PmMB4zLGJUDF77gEWdqWP28f3jHIefwVaRXQTPY3Bl0KS7WTZ2EBhuMzcuRtqcOT7NustYyYZMpvI3vWeh1fzdT1ujdKzIOp8rgH5VtcuKRNiOIzzQzjgrtzwcHYQ2oPnMUTv5l3cYOzdVG8krDfQpNgeljzDjxylgTpzZUcHO6JhkJliqMuKwxi0r287T9Wf2+F0o2BSwpJLtmGIKhkeYsStOGl/ibZdydskqcHDFy4st9zyFuy8xMdSK1tmXcYV6eFZ/lxbjAYUJ9JPILUvMKmgsFyX6UOsVJ9k3afN96WP5Do/43EIQeeFmmYGco8C9ntc8ewWXMiZU7U1lx0tgP7fUhzB8GWGCJPOR68rhbUpn4tyMviX1Eto3S7h0g1Fprxq5aC2c/8gIXGD2XQvzgXVhoBICoq5T8OHPFk7DM9XBBY2wJ98NSRAEIspZrxvn9vrBFWy53lP0dcij86pbkEPfGn6wZQoF1G8gzhZuxv51nVBqq8MsDTgQtr+blAvzmKrM6PktQUE6KRJKlUvvxJP9Zlj58D/6QDX1CT66ehkxk33T6pwjd1T21yUjsQfRRdfZoNKtcBbjsmk1qpcTB19keDJEY="
  # Location Lookup API key
  - secure: "simbAEsqg97G0Yol6CQCfIhyWsFX9ptIxRJ1+RaHe3snpXvWnSfIICo6q3tw8m5uAHgPD7/9WaS2vzybUEyFS9V7XnyFvmnTXfc9KHrPQnjdOg8K41k4gH8gRioiVQNawmQiw9Z6A6ZlBJfiMYXac6rKvqyc3n1bLzbGuGGmxfbxJQVT6EKjLXpC16JliyUL6sFIwlJ58Jz7MsKRS/AxiWzD4q8OE8VFKwW7v0ahnJ0jTbDHGRRz8ftvTjSl+LTLwRS9FDmFRxC1r5FIKlzUYnF+hq8nby0BXvfU/2xEcZYWgpoL9YpCM1Ru5VDub5F1jKZ+MUdImS6GA6rXYKHz3322KxrhnjhmvXBGVLH66UrX1pCp7TFiDy7AwRKl6EpEarvRnzhKNAM3WO87xpWNNyyNtdABb9XvBiSq41t1jjrCEeT4gbWogkpJIaODjrAcJN4cEwdbrzdQ9OQrRmdtflAHvWgZsGPhRV6oGYgGqHB80b68Yp58lNAE8pao6LXNI1jTiTAtBWNVd1RARl8I1emp61p/09nE7GHOFIRu3eIX/hSVTS/jpG6oa/nm7TfikYuyJOWxFlJEndz6zW0e0ISLKyDECondsfvWACKF3ILmHIZU8xvb+OHgU8sBUTSKwZueGKNNzCV5EFMn5b3ualLDRgjNRLcvg+MDADr6x8c="

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
- composer test -- --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache
